#pragma once

/* Source: official 4.3B-BOX ESP-IDF 08_lvgl_Porting/main/waveshare_rgb_lcd_port.h */
#define BOARD_LCD_RGB_VSYNC_GPIO 3
#define BOARD_LCD_RGB_HSYNC_GPIO 46
#define BOARD_LCD_RGB_DE_GPIO 5
#define BOARD_LCD_RGB_PCLK_GPIO 7
#define BOARD_LCD_RGB_DATA0_GPIO 14
#define BOARD_LCD_RGB_DATA1_GPIO 38
#define BOARD_LCD_RGB_DATA2_GPIO 18
#define BOARD_LCD_RGB_DATA3_GPIO 17
#define BOARD_LCD_RGB_DATA4_GPIO 10
#define BOARD_LCD_RGB_DATA5_GPIO 39
#define BOARD_LCD_RGB_DATA6_GPIO 0
#define BOARD_LCD_RGB_DATA7_GPIO 45
#define BOARD_LCD_RGB_DATA8_GPIO 48
#define BOARD_LCD_RGB_DATA9_GPIO 47
#define BOARD_LCD_RGB_DATA10_GPIO 21
#define BOARD_LCD_RGB_DATA11_GPIO 1
#define BOARD_LCD_RGB_DATA12_GPIO 2
#define BOARD_LCD_RGB_DATA13_GPIO 42
#define BOARD_LCD_RGB_DATA14_GPIO 41
#define BOARD_LCD_RGB_DATA15_GPIO 40

#define BOARD_CH422G_I2C_SCL_GPIO 9
#define BOARD_CH422G_I2C_SDA_GPIO 8

/* Source: official 4.3B-BOX ESP-IDF 03_SD_Test/sdkconfig.defaults */
#define BOARD_SD_SPI_MOSI_GPIO 11
#define BOARD_SD_SPI_MISO_GPIO 13
#define BOARD_SD_SPI_CLK_GPIO 12

#define BOARD_TOUCH_INTERRUPT_GPIO 4
#define BOARD_TOUCH_RESET_EXPANDER_CHANNEL 1
#define BOARD_LCD_RESET_EXPANDER_CHANNEL 3
#define BOARD_BACKLIGHT_EXPANDER_CHANNEL 2
#define BOARD_ISOLATED_DI0_EXPANDER_CHANNEL 0
#define BOARD_ISOLATED_DI1_EXPANDER_CHANNEL 5
#define BOARD_ISOLATED_DO0_EXPANDER_CHANNEL 8
#define BOARD_ISOLATED_DO1_EXPANDER_CHANNEL 9
