#pragma once

#define BOARD_LCD_HORIZONTAL_RESOLUTION 800
#define BOARD_LCD_VERTICAL_RESOLUTION 480
#define BOARD_LCD_PIXEL_CLOCK_HZ 16000000
#define BOARD_LCD_HSYNC_PULSE_WIDTH 4
#define BOARD_LCD_HSYNC_BACK_PORCH 8
#define BOARD_LCD_HSYNC_FRONT_PORCH 8
#define BOARD_LCD_VSYNC_PULSE_WIDTH 4
#define BOARD_LCD_VSYNC_BACK_PORCH 8
#define BOARD_LCD_VSYNC_FRONT_PORCH 8
#define BOARD_LCD_PCLK_ACTIVE_NEGATIVE 1
