#pragma once

#define BOARD_SHARED_I2C_SCL_GPIO 7
#define BOARD_SHARED_I2C_SDA_GPIO 15
#define BOARD_LCD_SERIAL_SDA_GPIO 1
#define BOARD_LCD_SERIAL_SCL_GPIO 2
#define BOARD_LCD_SERIAL_CS_GPIO 42
#define BOARD_TOUCH_INTERRUPT_GPIO -1
#define BOARD_TOUCH_RESET_EXPANDER_CHANNEL 1
#define BOARD_LCD_RESET_EXPANDER_CHANNEL 3
#define BOARD_SYSTEM_ENABLE_EXPANDER_CHANNEL 5
#define BOARD_BUZZER_ENABLE_EXPANDER_CHANNEL 6
#define BOARD_RTC_INTERRUPT_EXPANDER_CHANNEL 7
#define BOARD_SDMMC_CLK_GPIO 2
#define BOARD_SDMMC_CMD_GPIO 1
#define BOARD_SDMMC_D0_GPIO 4
#define BOARD_RS485_TX_GPIO 44
#define BOARD_RS485_RX_GPIO 43
#define BOARD_CAN_TX_GPIO 6
#define BOARD_CAN_RX_GPIO 0
